# Generated by Django 5.2.15 on 2026-06-25 04:46

import django.core.validators
import django.db.models.deletion
import spaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_alter_spacereview_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacereview',
            name='score_comfort',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), spaces.models.validate_half_step]),
        ),
        migrations.AlterField(
            model_name='spacereview',
            name='score_noise',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), spaces.models.validate_half_step]),
        ),
        migrations.AlterField(
            model_name='spacereview',
            name='score_plug',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), spaces.models.validate_half_step]),
        ),
        migrations.AlterField(
            model_name='spacereview',
            name='score_wifi',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), spaces.models.validate_half_step]),
        ),
        migrations.AddConstraint(
            model_name='spacereview',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_review_per_user'),
        ),
    ]
