# Generated by Django 5.2.15 on 2026-06-29 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_spacereview_user_alter_spacereview_score_comfort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafereviewraw',
            name='crawled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
